### ISSUE TITLE
rudolph does not work with hareactive v2.1

### ISSUE THREAD

**Issue by vrobinson** [funkia/rudolph#2]
I am aware that hareactive 1.5 is a peer dependency for rudolph.

I was able to keep rudolph working locally by making a tiny tweak to the JavaScript output (note that I only ran a small set of tests against this change). This source maps to line 80 of rudolph.ts in the original source where the fix is to

change:
```javascript
    locationB.push(path);
```
to:
```javascript
    locationB.newValue(path);
```

I forked the code and was going to submit this little fix back, but when I edited the .ts file I discovered that it will not compile. The reason is because hareactive only exposes the base class Behavior< A> as the return value of behaviorFromEvent instead of the type that it creates DomEventBehavior< A> or the intermediate type ProducerBehavior< A> which is where newValue() is exposed, so my fix works in JavaScript because that's the object that is really there at runtime, but it won't compile in TypeScript because the derived type is not exposed as the result of this function.

I don't know what designs you have in mind such as if you want behaviorFromEvent to expose the full underlying types or if you have other ideas for how rudolph should work here so I'm sending this to you as an issue instead.

**Comment by limemloh** [comment]
Thank you for making me aware of this.

I have used your fix and updated the dependencies, updated the examples to use the current lastest version of Hareactive and Turbine in release 0.0.6.
